# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('language', models.CharField(blank=True, choices=[(b'1', b'English'), (b'2', b'Kurmanji'), (b'3', b'Punjabi'), (b'4', b'Dari'), (b'5', b'Urdu'), (b'6', b'Arabic'), (b'7', b'Farsi'), (b'8', b'Greek'), (b'9', b'Sourani')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('registration_id', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
